window.DEMO_MEMBERS = [
  {
    "id": "m001",
    "username": "pradip.pariyar",
    "full_name": "pradip pariyar",
    "headline": "Based in Germany and I have been working in the aftermarket automotive industry for 8 years as a Senior Cloud Engineer",
    "company": "",
    "location": "Germany",
    "bio": "I am Pradip, based in Germany and I have been working in the aftermarket automotive industry for 8 years as a Senior Cloud Engineer",
    "building": "I would like to start my own business like a completely started Software-based supermarket. The ideas should work in a high-tech city like Bangalore and Hyderabad and other cities.   I have seen this concept currently operated in China and Malaysia",
    "skills": [
      "Software",
      "Cloud / DevOps",
      "Engineering",
      "Automotive / Mobility",
      "Startups / Business",
      "Food / Retail"
    ],
    "can_help": "Engineering/Coding",
    "looking_for": "I would like to explore more ideas 💡 from the group as well",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m002",
    "username": "sumit.sharma",
    "full_name": "Sumit Sharma",
    "headline": "I’ve 8 years of IT experience in Banking domain and I am currently based in Frankfurt",
    "company": "",
    "location": "Frankfurt",
    "bio": "I’ve 8 years of IT experience in Banking domain and I am currently based in Frankfurt",
    "building": "GenAI is everywhere and I really enjoy vibe coding 🙂. I haven’t built anything outside of work yet, but I love collaborating with people and actually turn ideas into reality",
    "skills": [
      "AI / GenAI",
      "Software",
      "Finance / Banking",
      "Design / UX"
    ],
    "can_help": "I have mainly worked on the development side. Recently, I have also been preparing myself with design-thinking models to help turn ideas into something practical and useful",
    "looking_for": "That as I joined this group with high hopes—to collaborate and build something meaningful with some of you, and continue working or connected in the long run",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m003",
    "username": "sudarshan.bargaje",
    "full_name": "Sudarshan Bargaje",
    "headline": "Heat transfer and environment friendly technologies.",
    "company": "",
    "location": "Karlsruhe",
    "bio": "I am Mechanical engineer having around 12 year experience in renewable power , heat transfer and environment friendly technologies. I am freelancer  having business in India along with my own GmbH firm recently registered in Karlsruhe. I am mostly like half time India and half time EU",
    "building": "Engineering technologies related to Mechanical,  electrical and electronics field. RnD engineered with new future product development and launching",
    "skills": [
      "Software",
      "Product",
      "Engineering",
      "Finance / Banking",
      "Startups / Business",
      "Marketing / Growth"
    ],
    "can_help": "I can help anyone related to my field or looking for setting up own business in DE along with legal and tax part",
    "looking_for": "A good network /support / agencies / mostly marketing side to distribute and help expand my products. Any leads in space or water  heating/cooling will be helpful",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m004",
    "username": "jai.suveer.jain",
    "full_name": "Jai Suveer Jain",
    "headline": "I’m based in Berlin. I have 5 years of work experience as a Cloud Engineer working in India, Nigeria and Germany in Telecommunications background.…",
    "company": "",
    "location": "Berlin",
    "bio": "I’m based in Berlin. I have 5 years of work experience as a Cloud Engineer working in India, Nigeria and Germany in Telecommunications background. I am also an influencer on Instagram with 75000 followers",
    "building": "I am trying to build a tech based platform to connect food lovers in different cities. The idea initially was to convert my followers from instagram to users of my application. I am also exploring other ideas how to successfully implement this or any other ideas where I can contribute",
    "skills": [
      "Cloud / DevOps",
      "Data / Analytics",
      "Engineering",
      "Startups / Business",
      "Food / Retail",
      "Community / Networking"
    ],
    "can_help": "I am good in creating attention of people by creative ideas to drag users to beta or testing phase products. I have my Masters in Data Analytics and try to think analytically",
    "looking_for": "I am looking for ideas for startups, attending startup events or any such things which is in Europe and could be implemented in India",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m005",
    "username": "janardhan",
    "full_name": "Janardhan",
    "headline": "An Investment banker for 2 decades, Startup Investor and Business",
    "company": "",
    "location": "",
    "bio": "An Investment banker for 2 decades, Startup Investor and Business",
    "building": "AI enabled Fintech, Green energy and Data optimisation",
    "skills": [
      "AI / GenAI",
      "Data / Analytics",
      "Finance / Banking",
      "Startups / Business",
      "Energy / Climate",
      "Community / Networking"
    ],
    "can_help": "Building Business, through network and scaling through bottom up approach",
    "looking_for": "Network with community and build Tech enabled business",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m006",
    "username": "yatharth.joshi",
    "full_name": "Yatharth Joshi",
    "headline": "I am currently applying for full-time opportunities in my field.",
    "company": "",
    "location": "Stuttgart",
    "bio": "I am based in Esslingen (near Stuttgart). I am living in Germany since 2 years now. I have recently completed my master's degree in Design and Development in Automotive and Mechanical engineering from Hochschule Esslingen. Also, I am currently applying for full-time opportunities in my field.",
    "building": "Not building anything specific at the moment. Mainly here to get inspired and discover the possibilities and use of GenAI tools in creating a full-fledged product.",
    "skills": [
      "AI / GenAI",
      "Software",
      "Product",
      "Engineering",
      "Automotive / Mobility",
      "Design / UX"
    ],
    "can_help": "Happy to provide honest, non-judgmental opinions and reviews regarding your ideas.",
    "looking_for": "To be in company of like-minded people.",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m007",
    "username": "prashant.shah",
    "full_name": "Prashant Shah",
    "headline": "I’m based in Stuttgart. I have been involved in 4 Ventures earlier, and running my 5th right now, looking for collaborators for 6th one. So, I…",
    "company": "",
    "location": "Stuttgart",
    "bio": "I’m based in Stuttgart. I have been involved in 4 Ventures earlier, and running my 5th right now, looking for collaborators for 6th one. So, I started this \"Startup Enthusiasts\" Community out of my own need :)",
    "building": "Like many of you, I’m deep into the GenAI space right now. :) I’m currently building a small app for my son and I also run https://nritravelbuddy.com/",
    "skills": [
      "AI / GenAI",
      "Software",
      "Startups / Business",
      "Sales / GTM",
      "Community / Networking"
    ],
    "can_help": "My background is all about Execution. I can help you think through how to actually build and launch, specifically when it comes to Go-to-Market (GTM) strategy.",
    "looking_for": "Honestly, just to be in the company of like-minded, passionate people. Building can be lonely, and I want to be part of a tribe that pushes each other forward.",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m008",
    "username": "naveen.chand",
    "full_name": "Naveen Chand",
    "headline": "I tech enthusiast, with 6+ year’s fullstack devops experience with masters degree.",
    "company": "",
    "location": "",
    "bio": "I tech enthusiast, with 6+ year’s fullstack devops experience with masters degree. Been part of university startup accelerator program and have some experience about pitching",
    "building": "LLMs and application/ product development for productivity across various sectors",
    "skills": [
      "Software",
      "Cloud / DevOps",
      "Product",
      "Startups / Business",
      "Education",
      "Community / Networking"
    ],
    "can_help": "Architecting simplest and scalable MVP and prototyping with web technologies.",
    "looking_for": "Networking & possible collaboration",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m009",
    "username": "khushboo.khairkar",
    "full_name": "Khushboo Khairkar",
    "headline": "I’m Khushboo, based in Germany.",
    "company": "",
    "location": "Germany",
    "bio": "I’m Khushboo, based in Germany. I’m an Automotive Test & Automation Engineer with ~4+ years of experience working on ECU testing, diagnostics, and test automation across global OEM projects.",
    "building": "I’m deeply interested in building AI-driven test automation tools and scalable engineering solutions that reduce manual effort and improve quality. Over time, I’ve had multiple startup ideas, I even started building a few apps, but paused them midway due to lack of guidance and the right ecosystem. Now, I’m consciously getting back into building, with a clearer mindset and stronger intent to take things to completion.",
    "skills": [
      "AI / GenAI",
      "Software",
      "Product",
      "Engineering",
      "Automotive / Mobility",
      "Startups / Business"
    ],
    "can_help": "I can help with execution-heavy tech problems, breaking vague ideas into clear systems, workflows, and MVPs. I bring strong hands-on experience in automation, Python-based frameworks, diagnostics, and I’m also comfortable coding and building apps using AI to quickly prototype and validate ideas.",
    "looking_for": "To build something meaningful with like-minded people who share the same motivation and drive, individuals who value learning, honest feedback, and long-term thinking, and are serious about building consistently, not just ideating.",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m010",
    "username": "soumajit.majumder",
    "full_name": "Soumajit Majumder",
    "headline": "VLMs, etc. in the context of Embodied AI.",
    "company": "",
    "location": "",
    "bio": "I am a AI Researcher at Huawei working on diffusion models, VLMs, etc. in the context of Embodied AI.",
    "building": "Computer Vision Systems, Financial Markets",
    "skills": [
      "AI / GenAI",
      "Finance / Banking",
      "Design / UX"
    ],
    "can_help": "AI/ML architecture design",
    "looking_for": "Meaningful projects to contribute to",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m011",
    "username": "onkar.patil",
    "full_name": "Onkar Patil",
    "headline": "Tech. Strategy.",
    "company": "",
    "location": "",
    "bio": "I am mechanical engineer turned business consultant. I love to solve complex business problems and bring structure to them. I am currently working in the areaof operating model design, Tech. Strategy.",
    "building": "I am passionate about business building, i love to scale up things, set up operations, define strategies and develop growth trajectories.",
    "skills": [
      "Engineering",
      "Startups / Business",
      "Marketing / Growth",
      "Design / UX",
      "Operations / Supply Chain",
      "Community / Networking"
    ],
    "can_help": "I can help you with validating ideas, by building MVPs, consuct market research, define ad develop processes, develop startegies and execute them.",
    "looking_for": "I am looking for a community to exchange ideas, build something together with like minded people.",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m012",
    "username": "parvesh.taneja",
    "full_name": "Parvesh TANEJA",
    "headline": "A Mechanical & Mechatronics Engineer with 7+ years of R&D and product development experience.",
    "company": "",
    "location": "",
    "bio": "My name is Parvesh Taneja, a Mechanical & Mechatronics Engineer with 7+ years of R&D and product development experience. I’m currently based in Vienna (I keep travelling to nearby countries) and have worked across design, prototyping, and manufacturing.",
    "building": "I’m building ORBEE, a smart, modular indoor farming system focused on urban homes and apartments. The goal is to make indoor food growing automated, scalable, and aesthetically pleasing by combining mechatronics, IoT, and modular product design.",
    "skills": [
      "Software",
      "Product",
      "Engineering",
      "Startups / Business",
      "Sales / GTM",
      "Design / UX"
    ],
    "can_help": "Product design (CAD & Simulations) & engineering (mechanical design, DFM/DFA, prototyping), system architecture for hardware-based startups, and turning concepts into manufacturable products.",
    "looking_for": "Like-minded collaborators/co-founders, especially in Embedded software/IoT, and go-to-market strategy/Business Development, as well as early-stage startup discussions and feedback.",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m013",
    "username": "suraj.sonar",
    "full_name": "Suraj sonar",
    "headline": "Im suraj sonar, living in Germany since 2014 with my wife and 2 children.",
    "company": "",
    "location": "Wiesbaden",
    "bio": "Im suraj sonar, living in Germany since 2014 with my wife and 2 children. Im running a indo nepali restaurant in majnz kastel , Wiesbaden. Im an MBA from Pune University in the year 2003. I have overall 30 years experience i. Corporate and as an entrepreneur.",
    "building": "Im looking for expand my business and looking for a active partner to take my business further.",
    "skills": [
      "Software",
      "Startups / Business",
      "Sales / GTM",
      "Marketing / Growth",
      "Food / Retail",
      "Education"
    ],
    "can_help": "Im good Marketing and sales person who have rich experience in hospitality industry and business development.",
    "looking_for": "I can guide and shape up others career or business opportunities with my rich experience",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m014",
    "username": "pradeep",
    "full_name": "Pradeep",
    "headline": "Product manager",
    "company": "",
    "location": "",
    "bio": "Product manager",
    "building": "Looking to connect with other startup founders",
    "skills": [
      "Product",
      "Startups / Business",
      "Community / Networking"
    ],
    "can_help": "Product management and advice on building new product",
    "looking_for": "Networking",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m015",
    "username": "onkar.magdum",
    "full_name": "Onkar Magdum",
    "headline": "India. Living here since last 5 years.",
    "company": "",
    "location": "Germany",
    "bio": "I am analyst by profession looking to start a startup here in Germany. Originally from Maharashtra, India. Living here since last 5 years.",
    "building": "Tech startup mainly related to Carbon economy.",
    "skills": [
      "Data / Analytics",
      "Startups / Business",
      "Community / Networking"
    ],
    "can_help": "Business legals/rules",
    "looking_for": "Connect to like minded people and get help in various niche.",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m016",
    "username": "chandni.patel",
    "full_name": "Chandni patel",
    "headline": "I have a small start up in Lusaka ,zambia and will be soon moving to Germany on opportunity card.i am interested in exploring more options for a…",
    "company": "",
    "location": "Germany",
    "bio": "I have a small start up in Lusaka ,zambia and will be soon moving to Germany on opportunity card.i am interested in exploring more options for a small start up business",
    "building": "My own start up business",
    "skills": [
      "Startups / Business",
      "Community / Networking"
    ],
    "can_help": "Good at best customer service",
    "looking_for": "Community support to keep me on right track and give me correct guidance",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m017",
    "username": "chetan.kapoor",
    "full_name": "Chetan Kapoor",
    "headline": "I'm Chetan Kapoor from Haryana, India.",
    "company": "",
    "location": "Munich",
    "bio": "I'm Chetan Kapoor from Haryana, India. I'm DevOps Engineer based in Munich.",
    "building": "Photography",
    "skills": [
      "Cloud / DevOps",
      "Engineering",
      "Startups / Business"
    ],
    "can_help": "Photography related questions, business registration in Germany etc",
    "looking_for": "Getting some help and ideas",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m018",
    "username": "murtuza.godil",
    "full_name": "MURTUZA GODIL",
    "headline": "Mechatronics Engineer Experience in automation and sales engineering",
    "company": "",
    "location": "",
    "bio": "Mechatronics Engineer Experience in automation and sales engineering",
    "building": "Right now nothing due to job search",
    "skills": [
      "Engineering",
      "Startups / Business",
      "Sales / GTM"
    ],
    "can_help": "Research And explaining products",
    "looking_for": "Helping Startup grow by providing help in research and sales",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m019",
    "username": "harshit",
    "full_name": "Harshit",
    "headline": "Experienced sap abap developer",
    "company": "",
    "location": "",
    "bio": "experienced sap abap developer",
    "building": "Sap",
    "skills": [
      "Software"
    ],
    "can_help": "Sap",
    "looking_for": "Learn about more technology and advancement",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m020",
    "username": "jagyaseni.das",
    "full_name": "Jagyaseni Das",
    "headline": "A student at FAU Erlangen-Nürnberg doing MS in Data Analytics & Entrepreneurship.",
    "company": "",
    "location": "Nuremberg",
    "bio": "A student at FAU Erlangen-Nürnberg doing MS in Data Analytics & Entrepreneurship. I was selected as one of top participants in FAU DTA batch 8 which is an elite program for entrepreneurship.",
    "building": "Med-Tech precisely",
    "skills": [
      "Data / Analytics",
      "Startups / Business",
      "Education",
      "Community / Networking"
    ],
    "can_help": "Communication and team building",
    "looking_for": "Networking with like-minded resources which can help me gain experience for Med-Tech startup",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m021",
    "username": "piyush.saini",
    "full_name": "Piyush Saini",
    "headline": "Community member open to meaningful collaboration",
    "company": "",
    "location": "",
    "bio": "I am a software architect. Started my company named ‘zenithsaini’",
    "building": "Started a company",
    "skills": [
      "Software"
    ],
    "can_help": "Problem solving.  Does not matter what",
    "looking_for": "Facebook",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m022",
    "username": "nitin.sethi",
    "full_name": "Nitin Sethi",
    "headline": "Community member open to meaningful collaboration",
    "company": "",
    "location": "Düsseldorf",
    "bio": "I am a blue card data analyst working in Düsseldorf. I like movies and hikes and can be a good hustler.",
    "building": "I am currently looking into export/ import opportunities in Germany especially as this FTA is finalized",
    "skills": [
      "Data / Analytics"
    ],
    "can_help": "I can help with market data analystics. I can also speak german so i can help in translating.",
    "looking_for": "I want to see if there are people in similar Synergien and benefit from it.",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m023",
    "username": "praveen",
    "full_name": "Praveen",
    "headline": "Community member open to meaningful collaboration",
    "company": "",
    "location": "",
    "bio": "I am a scientific project manager in the domain of atmospheric and space engineering",
    "building": "Sustainability solutions based on space tech",
    "skills": [
      "Engineering",
      "Energy / Climate"
    ],
    "can_help": "Project Management and critical analysis",
    "looking_for": "User need and knowledge base",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m024",
    "username": "anand",
    "full_name": "Anand",
    "headline": "Senior IT Project Manager with 20+ years of international experience leading complex IT programs and client-facing delivery engagements across…",
    "company": "",
    "location": "",
    "bio": "Senior IT Project Manager with 20+ years of international experience leading complex IT programs and client-facing delivery engagements across global organizations",
    "building": "I’m currently obsessed with building efficient, data-driven financial and operational systems that connect business strategy to actionable insights.",
    "skills": [
      "Data / Analytics",
      "Finance / Banking",
      "Startups / Business",
      "Community / Networking"
    ],
    "can_help": "I help teams streamline processes and implement effective financial and operational systems that drive efficiency and measurable results.",
    "looking_for": "I’m looking to connect with experienced founders and peers to learn from their successes and mistakes, and to refine my own ideas and strategies for impactful projects.",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m025",
    "username": "anusha",
    "full_name": "Anusha",
    "headline": "Enthusiastic about startups and more on learning side on process and ops",
    "company": "",
    "location": "",
    "bio": "Enthusiastic about startups and more on learning side on process and ops",
    "building": "I have some ideas, not concrete yet",
    "skills": [
      "Education"
    ],
    "can_help": "I don't know",
    "looking_for": "Information",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m026",
    "username": "farhat",
    "full_name": "Farhat",
    "headline": "Community member open to meaningful collaboration",
    "company": "",
    "location": "",
    "bio": "I am Software Architect",
    "building": "Web development and Gen AI",
    "skills": [
      "AI / GenAI",
      "Software",
      "Product",
      "Community / Networking"
    ],
    "can_help": "Networking and Project development",
    "looking_for": "Build a product",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m027",
    "username": "gokulakrishnan.balaji",
    "full_name": "Gokulakrishnan Balaji",
    "headline": "T shaped Performance Marketing Specialist & an Entrepreneur",
    "company": "",
    "location": "",
    "bio": "T shaped Performance Marketing Specialist & an Entrepreneur",
    "building": "I’m deeply passionate about building brands from zero to one, I enjoy understanding how people think, how products are used, and then designing processes, marketing, or technology that removes friction. What excites me most is the combination of creativity and discipline",
    "skills": [
      "Startups / Business",
      "Marketing / Growth"
    ],
    "can_help": "Paid media marketing and Brand strategies",
    "looking_for": "Looking for projects and opportunities",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m028",
    "username": "palak.k.lakhani",
    "full_name": "Palak K. Lakhani",
    "headline": "Founder and entrepreneur based in Germany, building businesses across community services, events, and real estate.",
    "company": "",
    "location": "Germany",
    "bio": "Founder and entrepreneur based in Germany, building businesses across community services, events, and real estate. Background in Chemical Engineering and Polymer Materials Science, with hands-on experience in execution, operations, and growth.",
    "building": "Building Indo-German Konnekt (IGK) as a one-stop platform for expats in Germany, covering events, integration, and community services. In parallel, scaling Lakhani Vermietung & Dienstleistungen, focused on compliant rental, subletting, and hospitality solutions. Strong focus on systems, legal clarity, and sustainable growth.",
    "skills": [
      "Engineering",
      "Startups / Business",
      "Sales / GTM",
      "Marketing / Growth",
      "Legal / Compliance",
      "Operations / Supply Chain"
    ],
    "can_help": "Launching and structuring businesses in Germany, especially in events, rentals, and expat-focused services. I’m good at turning ideas into executable models, handling operations, partnerships, compliance basics, and go-to-market strategy.",
    "looking_for": "Meaningful connections with operators and collaborators. I’m here to exchange knowledge, find strategic partnerships, and learn from people who are serious about building long-term, real-world businesses.",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m029",
    "username": "khem",
    "full_name": "Khem",
    "headline": "Community member open to meaningful collaboration",
    "company": "",
    "location": "",
    "bio": "I am DeFAI enthusiast.",
    "building": "DeFAI project",
    "skills": [
      "Finance / Banking"
    ],
    "can_help": "Decentralize finance",
    "looking_for": "Like minded people",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m030",
    "username": "sharath.prakash",
    "full_name": "Sharath Prakash",
    "headline": "Community member open to meaningful collaboration",
    "company": "",
    "location": "Germany",
    "bio": "I am a software engineer. Looking for a way for entrepreneurship of owning things",
    "building": "Building cloud native",
    "skills": [
      "Software",
      "Cloud / DevOps",
      "Engineering",
      "Startups / Business"
    ],
    "can_help": "Technical expertise",
    "looking_for": "How to setup things in germany",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m031",
    "username": "puneet.amin",
    "full_name": "Puneet Amin",
    "headline": "Working professional starting a new business",
    "company": "",
    "location": "Germany",
    "bio": "Working professional starting a new business",
    "building": "SaaS solutions and AI",
    "skills": [
      "AI / GenAI",
      "Software",
      "Startups / Business",
      "Sales / GTM",
      "Marketing / Growth"
    ],
    "can_help": "AI for sales and marketing",
    "looking_for": "Guidance on starting a business in Germany",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m032",
    "username": "abdul.quadeer.mohammed",
    "full_name": "Abdul Quadeer Mohammed",
    "headline": "Community member open to meaningful collaboration",
    "company": "",
    "location": "",
    "bio": "I am tech enthusiast who is always trying to learn new things (like AI..) and try to be uptodate with the market.",
    "building": "Scouting and exploring new things, Photography and learning about people and experiences.",
    "skills": [
      "AI / GenAI",
      "Startups / Business",
      "Education"
    ],
    "can_help": "Ideation, Good at learning, adapting and communication.",
    "looking_for": "Learning the experiences from others who have startups, established business or even ideas which can be materialized.",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m033",
    "username": "dr.ali.abas.wani",
    "full_name": "Dr. Ali Abas Wani",
    "headline": "Am a passionate and detail-oriented food scientist dedicated to developing innovative food products that promote health and wellness.",
    "company": "",
    "location": "Munich",
    "bio": "am a passionate and detail-oriented food scientist dedicated to developing innovative food products that promote health and wellness. I specialize in applying consumer science to identify and address defects in food products, ensuring quality, safety, and customer satisfaction. I am driven by research, continuous improvement, and creating nutritious solutions that meet evolving consumer needs.\n\nFood Scientist by profession, based in Munich",
    "building": "Consumer health\n\nCurrently building Desi Fresh Supermarket  with co founder Dr. Preeti Singh based on Traceability and Quality Management for better consumer assurance. Opened the first store in Munich",
    "skills": [
      "Software",
      "Product",
      "Startups / Business",
      "Healthcare / Life Sciences",
      "Food / Retail"
    ],
    "can_help": "Food product development and startup formation",
    "looking_for": "IT solutions for food bhsinesses\n\nI am looking for new partners across other big cities in Germany",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m034",
    "username": "raghav.bajaj",
    "full_name": "Raghav Bajaj",
    "headline": "Community member open to meaningful collaboration",
    "company": "",
    "location": "",
    "bio": "I am Founder of HumanlessLab which provides ai services to businesses",
    "building": "Learning and sharing thoughts on ai",
    "skills": [
      "AI / GenAI",
      "Startups / Business",
      "Education"
    ],
    "can_help": "Helping people automate and get productive",
    "looking_for": "By connecting people helping them solve their problems",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m035",
    "username": "harish",
    "full_name": "Harish",
    "headline": "Mechanical engineer",
    "company": "",
    "location": "",
    "bio": "Mechanical engineer",
    "building": "Startup Enthusiast",
    "skills": [
      "Software",
      "Engineering",
      "Startups / Business",
      "Sales / GTM",
      "Community / Networking"
    ],
    "can_help": "Business development",
    "looking_for": "Connect with Startups or co founders",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m036",
    "username": "nivi.kolatte",
    "full_name": "Nivi Kolatte",
    "headline": "Enterprise Cloud Architect with 16+ years experience in building scalable cloud platforms.",
    "company": "",
    "location": "",
    "bio": "Enterprise Cloud Architect with 16+ years experience in building scalable cloud platforms. Deep expertise in Azure, infrastructure automation, and emerging technologies. Currently transitioning to tech entrepreneurship as a co-founder.",
    "building": "Building AI/LLM solutions for enterprise banking and finance. Developing RAG-based systems for contract analysis and document processing.",
    "skills": [
      "AI / GenAI",
      "Cloud / DevOps",
      "Product",
      "Finance / Banking",
      "Startups / Business",
      "Sales / GTM"
    ],
    "can_help": "Enterprise architecture",
    "looking_for": "Co-founders with complementary skills (product, marketing, sales), networking with experienced founders in AI/fintech space, strategic guidance on scaling from MVP to product-market fit, and collaboration opportunities on infrastructure-as-a-service solutions.",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m037",
    "username": "ateet",
    "full_name": "Ateet",
    "headline": "Founder builder creating AI systems that work in the real world AI agents, voice agents, RAG apps, and automations.",
    "company": "",
    "location": "",
    "bio": "Founder builder creating AI systems that work in the real world AI agents, voice agents, RAG apps, and automations. Obsessed with speed, quality, and measurable impact.",
    "building": "Passionate about the AI revolution and how founders can turn it into real products. Currently building AI agents and automation systems.",
    "skills": [
      "AI / GenAI",
      "Startups / Business"
    ],
    "can_help": "Helping teams adopt AI safely: use-case selection, architecture, implementation, and measurable ROI.",
    "looking_for": "Meaningful connections, honest feedback, and collaboration opportunities to build and ship faster.",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m038",
    "username": "samyukthaa",
    "full_name": "Samyukthaa",
    "headline": "Community member open to meaningful collaboration",
    "company": "",
    "location": "",
    "bio": "I am a Full stack developer ; Co founded a digital services agency and a Masters student",
    "building": "Interesting Web / Mobile applications",
    "skills": [
      "Software",
      "Education"
    ],
    "can_help": "Web dev + QA",
    "looking_for": "Knowledge and new leads",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m039",
    "username": "anit",
    "full_name": "Anit",
    "headline": "DTC, eCommerce and Digital Marketing tech enthusias",
    "company": "",
    "location": "",
    "bio": "DTC, eCommerce and Digital Marketing tech enthusias",
    "building": "Blogging about a niche",
    "skills": [
      "Marketing / Growth"
    ],
    "can_help": "eCommerce, DTC and Digital Marketing",
    "looking_for": "Experiences and inspiration",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m040",
    "username": "arvind",
    "full_name": "Arvind",
    "headline": "10+ years as a native mobile app developer , TPM with focus on data analytics in one of the big 5 firms",
    "company": "",
    "location": "India",
    "bio": "10+ years as a native mobile app developer , TPM with focus on data analytics in one of the big 5 firms",
    "building": "Recently established a startup in India and expanding to US building smart fitness , community management and an intelligent supply chain app",
    "skills": [
      "Software",
      "Data / Analytics",
      "Product",
      "Startups / Business",
      "Operations / Supply Chain",
      "Community / Networking"
    ],
    "can_help": "Product management , Mobile app development and Data analytics",
    "looking_for": "Explore potential co-founder opportunities and identify potential clients for our products",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m041",
    "username": "siddharth.suman",
    "full_name": "Siddharth Suman",
    "headline": "CX-focused business innovator driving AI-powered product development and hospitality consulting, crafting transformative, customer-centric…",
    "company": "",
    "location": "",
    "bio": "CX-focused business innovator driving AI-powered product development and hospitality consulting, crafting transformative, customer-centric solutions with strategic precision and visionary leadership.",
    "building": "Cx product innovation & development.",
    "skills": [
      "AI / GenAI",
      "Software",
      "Product",
      "Startups / Business",
      "Marketing / Growth",
      "Community / Networking"
    ],
    "can_help": "I help transform customer experience strategies into AI-driven, revenue-focused innovations that elevate hospitality and startup product-driven businesses.",
    "looking_for": "I seek to actively contribute to a forward-thinking community, collaborating within a strategic think tank to co-create innovative revenue streams, scalable models, and transformative growth opportunities for fellow members. Discussing & developing innovative ideas to profitable products.",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m042",
    "username": "bhagyashree.mane",
    "full_name": "Bhagyashree Mane",
    "headline": "Community member open to meaningful collaboration",
    "company": "",
    "location": "Berlin",
    "bio": "I am a software engineer with a master's degree in signals and information processing and currently based in Berlin.",
    "building": "Currently I am exploring Agentic AI domain.",
    "skills": [
      "AI / GenAI",
      "Software",
      "Engineering",
      "Education",
      "Community / Networking"
    ],
    "can_help": "One thing I can help with developing deep learning models.",
    "looking_for": "Network with like minded people, brainstorm new ideas.",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m043",
    "username": "anusua.das",
    "full_name": "Anusua Das",
    "headline": "Originally from India, living in Germany for 11 years, working as Engineer for almost 10 years, and now more into Line Management in the last few…",
    "company": "",
    "location": "Germany",
    "bio": "Originally from India, living in Germany for 11 years, working as Engineer for almost 10 years, and now more into Line Management in the last few months.",
    "building": "Listening to others, dancing, people skills",
    "skills": [
      "Engineering"
    ],
    "can_help": "People skills, negotiations",
    "looking_for": "Enhance and engage into meaningful ideas, check with possibility to translate my idea to reality",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m044",
    "username": "gayatri.chavan",
    "full_name": "Gayatri Chavan",
    "headline": "I'm",
    "company": "",
    "location": "",
    "bio": "I'm",
    "building": "I'm looking to explore the markets for my passion of food, bringing healthy and fun agro products out in West to replace the paprika and salted world. It's just an idea right now. Also I'm artistic with various hobbies.",
    "skills": [
      "Startups / Business",
      "Food / Retail"
    ],
    "can_help": "I am very good listener and positive critic who can give you kind words of mental support when needed.",
    "looking_for": "Emotional ans - I want to find some motivation and hope to step out of 9-5 job and start something of my own as my chronic illness worsen my ability to work in corporate set up. Practical answer - guidance of how to go through with paperwork and bureaucracy of starting a startup.",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m045",
    "username": "jeevitha",
    "full_name": "jeevitha",
    "headline": "But previously I was anchor , event manager, social media manager",
    "company": "",
    "location": "Berlin",
    "bio": "I am student in Berlin, but previously I was anchor , event manager, social media manager",
    "building": "Community",
    "skills": [
      "Marketing / Growth",
      "Education",
      "Community / Networking"
    ],
    "can_help": "Administration",
    "looking_for": "Support",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m046",
    "username": "garima.aggarwal",
    "full_name": "Garima Aggarwal",
    "headline": "Community member open to meaningful collaboration",
    "company": "",
    "location": "",
    "bio": "I am Garima Aggarwal coming here as international student and pursue my bsc in healthcare management.",
    "building": "To start an own clothing business",
    "skills": [
      "Startups / Business",
      "Healthcare / Life Sciences",
      "Education"
    ],
    "can_help": "Friendly nature, reliable and hardworking",
    "looking_for": "Businees",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m047",
    "username": "alafiya.malak",
    "full_name": "Alafiya Malak",
    "headline": "I'm a sales professional focused on building meaningful connections and driving growth.",
    "company": "",
    "location": "",
    "bio": "Hi, I'm a sales professional focused on building meaningful connections and driving growth. I’m currently creating a women’s circle to bring together ambitious women for support, collaboration, and shared success.",
    "building": "Women Circle/ Event Management",
    "skills": [
      "Sales / GTM",
      "Marketing / Growth",
      "Community / Networking"
    ],
    "can_help": "Networking, communication.",
    "looking_for": "Get new ideas, opportunities.",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m048",
    "username": "satakshi.arora",
    "full_name": "Satakshi Arora",
    "headline": "I'm a Fashion Designer with 15 years experience (10 year entrepreneurial experience).",
    "company": "",
    "location": "",
    "bio": "I'm a Fashion Designer with 15 years experience (10 year entrepreneurial experience). I'm passionate and devoted about sustainable couture and wish to continue the journey here in DE. In my alter ego, I'm just as passionate about food and vegan fine dining cooking (opening a gourmet kitchen is my retirement plan) Cheers to dreaming big!",
    "building": "Sustainable Home Decor",
    "skills": [
      "Food / Retail",
      "Operations / Supply Chain",
      "Community / Networking"
    ],
    "can_help": "I'm good at mentoring small scale businesses about manufacturing, dos and don'ts, range plans etc",
    "looking_for": "Friendly brainstorming and networking",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m049",
    "username": "chetan.chetan",
    "full_name": "Chetan Chetan",
    "headline": "Community member open to meaningful collaboration",
    "company": "",
    "location": "",
    "bio": "I am a MBA student and want to built a sustainable business.",
    "building": "Anime Merchandise",
    "skills": [
      "Startups / Business",
      "Education"
    ],
    "can_help": "I am good at designing and also analytical thinking",
    "looking_for": "Some people who want to start business with me or offer some expertise",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m050",
    "username": "pradeepthi.kanukuntla",
    "full_name": "Pradeepthi Kanukuntla",
    "headline": "I'm Pradeepthi Kanukuntla, an NLP Master Practitioner, Healer, and Manifestation and Spiritual Coach, dedicated to empowering individuals to align…",
    "company": "",
    "location": "Germany",
    "bio": "I'm Pradeepthi Kanukuntla, an NLP Master Practitioner, Healer, and Manifestation and Spiritual Coach, dedicated to empowering individuals to align with their true potential. Every day, I support and guide more than 4,700+ people worldwide through free affirmations, switchwords, number codes, spiritual workshops, and the universal laws of manifestation.\n\nOver the years, I have had the privilege of helping countless individuals overcome personal challenges and achieve their heartfelt desires, whether it’s securing a dream job, receiving promotions, restoring marital harmony, improving academic performance, healing relationships, or even manifesting the joy of pregnancy. With a high success rate, my clients often experience tangible results and profound life transformations.\n\nAlongside personal consultations, I conduct powerful workshops and group sessions focused on:\n🌸 Health, wealth, and prosperity\n🌸 Family harmony and marital bliss\n🌸 Children’s education and academic success\n🌸 Abundance, love, and gratitude practices\n🌸 Navaratri workshops for spiritual growth\n🌸 Healing modalities like Ho’oponopono, gratitude, and protection techniques\n\nMy mission is simple yet profound: to guide you in manifesting your deepest wishes, embracing peace, love, and abundance, and creating a life filled with harmony and joy.\n\n🌟 If you’re ready to transform your reality and invite miracles into your life, I am here to walk this journey with you.\n\n✨️ Apart from this I'm a Community Leader for Telugu Moms Network Facebook community with 31K+ moms across the world. A social media influencer with strong presence across various social media platforms with more than 60K+ followers.",
    "building": "Want to reach out to more people here in Germany",
    "skills": [
      "Startups / Business",
      "Marketing / Growth",
      "Healthcare / Life Sciences",
      "Education",
      "Community / Networking"
    ],
    "can_help": "I'm good in comments skills, social media",
    "looking_for": "I'm looking on ideas how i can develp my business here in Germany",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m051",
    "username": "bharath",
    "full_name": "Bharath",
    "headline": "Engineer and also Entrepreneur based in Germany with experience in digital platforms and niche audience markets.",
    "company": "",
    "location": "Germany",
    "bio": "Engineer and also Entrepreneur based in Germany with experience in digital platforms and niche audience markets. Currently involved in building and scaling media related projects focused on community driven demand and distribution. Interested in exploring new business models and growth opportunities.",
    "building": "Currently focused on building platforms that connect underserved audiences with relevant content and experiences.",
    "skills": [
      "Engineering",
      "Startups / Business",
      "Marketing / Growth",
      "Education",
      "Operations / Supply Chain",
      "Community / Networking"
    ],
    "can_help": "I can help with validating ideas, understanding niche audiences, distribution strategies, and practical execution in early-stage businesses. I have hands on experience in working with partnerships, scaling operations, and bringing products/services to market.",
    "looking_for": "Looking to connect with like minded builders, exchange ideas, and gain insights into different industries and business models in Germany. Also interested in potential collaborations and learning from others’ experiences in scaling startups.",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m052",
    "username": "vignesh.soundararajan",
    "full_name": "Vignesh Soundararajan",
    "headline": "Am an engineer working for aerospace industries",
    "company": "",
    "location": "Germany",
    "bio": "Am an engineer working for aerospace industries",
    "building": "Business",
    "skills": [
      "Engineering",
      "Startups / Business"
    ],
    "can_help": "What I know about business",
    "looking_for": "Business ideas and legally handling in Germany",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m053",
    "username": "pradeep.kumar",
    "full_name": "Pradeep Kumar",
    "headline": "Startup enthusiastic, presently grinding as a PM",
    "company": "",
    "location": "",
    "bio": "Startup enthusiastic, presently grinding as a PM",
    "building": "Brands D2C, looking into export-import and consulting",
    "skills": [
      "Startups / Business",
      "Operations / Supply Chain"
    ],
    "can_help": "Ideating and operations",
    "looking_for": "Learn more and share",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m054",
    "username": "mamta",
    "full_name": "Mamta",
    "headline": "All, myself Mamta basically from Rajasthan India currently working as a office manager in berlin and hoping to have one day my own business here…",
    "company": "",
    "location": "Berlin",
    "bio": "Hello all, myself Mamta basically from Rajasthan India currently working as a office manager in berlin and hoping to have one day my own business here in Germany.",
    "building": "Want to build something like Ultra-Elite Concierge service company",
    "skills": [
      "Startups / Business",
      "Education"
    ],
    "can_help": "Researching",
    "looking_for": "Learning how to build a start up from scratch",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m055",
    "username": "amit.tiwari",
    "full_name": "Amit Tiwari",
    "headline": "Where I focus on building reliable and scalable solutions.",
    "company": "",
    "location": "",
    "bio": "My name is Amit. I’m a software developer currently working in the non-renewable energy sector, where I focus on building reliable and scalable solutions. Outside of work, I enjoy experimenting with new technologies, developing side project.",
    "building": "I have a background in machine learning.Currently experimenting with AI tools",
    "skills": [
      "AI / GenAI",
      "Software",
      "Product",
      "Energy / Climate",
      "Education",
      "Community / Networking"
    ],
    "can_help": "I can help with building and integrating AI/ML features into products.",
    "looking_for": "I am looking to connect with like-minded people to collaborate on ideas and build a viable product together.",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m056",
    "username": "ashish.kumar",
    "full_name": "Ashish Kumar",
    "headline": "Student cum developer ( developing Travelbuddy247 )",
    "company": "",
    "location": "",
    "bio": "Student cum developer ( developing Travelbuddy247 )",
    "building": "Currently i am developing Travelbuddy247 and there are currently 500 users",
    "skills": [
      "Software",
      "Design / UX",
      "Education"
    ],
    "can_help": "Coding and system design",
    "looking_for": "To get critical review of my platform",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m057",
    "username": "yash.gugaliya",
    "full_name": "Yash Gugaliya",
    "headline": "I'm Yash I'm studying Technology & Innovation Management.",
    "company": "",
    "location": "",
    "bio": "Hello I'm Yash \nI'm studying Technology & Innovation Management. I like to plan & organise engaging events.I'm a startup enthusiast who would like to build a startup (currently looking for idea) and maybe help others to expand and grow.",
    "building": "Building Network Groups",
    "skills": [
      "Startups / Business",
      "Education",
      "Community / Networking"
    ],
    "can_help": "Planning, Strategy building, Ideation till Execution.",
    "looking_for": "A log of Mentoring and learning.\nLooking for the missing pieces of the puzzle !",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m058",
    "username": "subhajit.sarkar",
    "full_name": "Subhajit Sarkar",
    "headline": "Retail, CPG, telecom, airlines and manufacturing-related environments.",
    "company": "",
    "location": "Germany",
    "bio": "I am an experienced Enterprise Data Architect and Data Governance leader with over a decade of experience across banking, retail, CPG, telecom, airlines and manufacturing-related environments.\nI combine strategic thinking with hands-on technology experience in cloud data platforms, analytics, governance and AI-enabled transformation.\nI enjoy turning complex business challenges into practical, scalable solutions and bringing business, technology and stakeholder teams together.\nI am keen to connect with founders, innovators and startup communities where I can contribute my enterprise experience, learn from others and help build meaningful, commercially viable products.",
    "building": "I am currently working towards with turning fragmented enterprise information into trusted, usable knowledge. \nI’m building an AI-enabled enterprise information retrieval system that helps people find accurate answers across databases, documents and business systems through simple natural-language questions.\n I’m passionate about practical AI, data governance and creating products that solve real operational problems—not just impressive demos. \nI also enjoy connecting with founders and builders who want to turn complex ideas into scalable, commercially meaningful solutions.",
    "skills": [
      "AI / GenAI",
      "Cloud / DevOps",
      "Data / Analytics",
      "Product",
      "Finance / Banking",
      "Startups / Business"
    ],
    "can_help": "I can help turn complex data and AI ideas into practical, scalable solutions—especially by shaping the architecture, governance, data strategy and business use cases needed to move from concept to a credible product.",
    "looking_for": "I am joining this community to connect with experienced founders, industry professionals and potential collaborators who are interested in building meaningful B2B technology solutions. \nIn particular, I’m looking to meet a potential co-founder based in Germany with strong domain expertise and networks in manufacturing, retail or CPG. \nMy goal is to combine that industry perspective with my background in enterprise data, AI and architecture to validate real market needs, shape a strong business model and build a scalable, commercially relevant startup.",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m059",
    "username": "yuvaraj",
    "full_name": "Yuvaraj",
    "headline": "Freelancer, innovative ideas which want to build as a product",
    "company": "",
    "location": "",
    "bio": "I am an software architect,  freelancer,  innovative ideas which want to build as a product",
    "building": "I have few ideas to SaaS based HCM product",
    "skills": [
      "Software",
      "Product"
    ],
    "can_help": "To share what is best or what is not as a",
    "looking_for": "To share their journey to avoid any mistakes and learn from that",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m060",
    "username": "neer.gala",
    "full_name": "Neer Gala",
    "headline": "Community member open to meaningful collaboration",
    "company": "",
    "location": "",
    "bio": "I am an enthusiast entrepreneur doing AI Automation and Ecommerce.",
    "building": "Currently working on my AI automation company building websites, chatbots and AI receptionists. Have some pilot clients but am still building my base and gathering more testimonials by offering some free services till my execution is prestine.\n\nApart from this working on some ecommerce projects on the side.",
    "skills": [
      "AI / GenAI",
      "Startups / Business",
      "Community / Networking"
    ],
    "can_help": "AI solutions. Primararily - Website,Chatbots, Automating Repetitive Admin tasks.",
    "looking_for": "Network with fellow entrepreneurs and potential clients.",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m061",
    "username": "nitish.kumar",
    "full_name": "Nitish Kumar",
    "headline": "Community member open to meaningful collaboration",
    "company": "",
    "location": "",
    "bio": "I am Engineer who has been working here for 4 years now and I am planning to open a business very soon.",
    "building": "It might sound funny but right now I am all about into cooking …",
    "skills": [
      "Engineering",
      "Startups / Business"
    ],
    "can_help": "Giving honest feedback I guess",
    "looking_for": "I am looking for some suggestions from already experienced founder",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m062",
    "username": "donal.shah",
    "full_name": "DONAL SHAH",
    "headline": "India. I am passionate about technology and eager to learn how real startups build and grow.",
    "company": "",
    "location": "India",
    "bio": "I am a 10th-grade student based in Ahmedabad, India. I am passionate about technology and eager to learn how real startups build and grow.",
    "building": "Learning how to use AI tools for practical work, including short video editing, basic program development, and social media marketing.",
    "skills": [
      "AI / GenAI",
      "Software",
      "Marketing / Growth",
      "Education"
    ],
    "can_help": "Creating simple promotional videos and social media ad content. I am fast at learning new tools and happy to assist with marketing tasks or general setup work.",
    "looking_for": "Mentors and collaborators who are building active projects, so I can learn from them, gain real-world experience, and contribute to a team.",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m063",
    "username": "nithin",
    "full_name": "Nithin",
    "headline": "Community member open to meaningful collaboration",
    "company": "",
    "location": "Berlin",
    "bio": "I am an engineer from India and  completed masters in Berlin",
    "building": "Kerala spices",
    "skills": [
      "Engineering"
    ],
    "can_help": "Hard work",
    "looking_for": "Contacts",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m064",
    "username": "vundavilli.ramesh",
    "full_name": "Vundavilli Ramesh",
    "headline": "I have expertise in pharmaceutical Quality Management System.",
    "company": "",
    "location": "Germany",
    "bio": "I have expertise in pharmaceutical Quality Management System.  Now I am looking to connect with the clients to do the business in India and Germany",
    "building": "I have few clients in India and looking to connect with them in a business partners.",
    "skills": [
      "Startups / Business",
      "Healthcare / Life Sciences",
      "Community / Networking"
    ],
    "can_help": "I am good in pharmaceutical Quality systems",
    "looking_for": "I am looking to similar interested people",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m065",
    "username": "madhi",
    "full_name": "Madhi",
    "headline": "AI Delivery Manager with 16 years experience in software industry",
    "company": "",
    "location": "",
    "bio": "AI Delivery Manager with 16 years experience in software industry",
    "building": "Startup Mentor",
    "skills": [
      "AI / GenAI",
      "Software",
      "Product",
      "Startups / Business"
    ],
    "can_help": "Mentor startup, Tech and product management",
    "looking_for": "May be I can join as part time cofounder if someone needs.",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m066",
    "username": "senthil.kumar",
    "full_name": "Senthil Kumar",
    "headline": "Full stack Software engineer trying to build something, currently boosted by AI",
    "company": "",
    "location": "",
    "bio": "Full stack Software engineer trying to build something, currently boosted by AI",
    "building": "AI powered SAAS application",
    "skills": [
      "AI / GenAI",
      "Software",
      "Engineering"
    ],
    "can_help": "Tech",
    "looking_for": "I want to learn from the experience of the group",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m067",
    "username": "manoj.kumar.baltha",
    "full_name": "Manoj Kumar Baltha",
    "headline": "I'm Manoj. Currently working as business analyst in Germany",
    "company": "",
    "location": "Germany",
    "bio": "I'm Manoj. Currently working as business analyst in Germany",
    "building": "I am currently obsessed with solving the post-visa \"black hole\" for international students moving to Germany. While getting a university admission and visa is a huge milestone, incoming students are left completely stranded when trying to find private housing from 6,000 miles away—exposing them to rampant rental scams and confusing German bureaucracy like city registration (Anmeldung). To fix this, I am building NextKin—a trusted hybrid onboarding platform that operates like \"TurboTax meets TaskRabbit\" for student relocation, combining automated paperwork with a 100% legal on-ground network of university graduates and student buddies.",
    "skills": [
      "Data / Analytics",
      "Startups / Business",
      "Education",
      "Legal / Compliance",
      "Community / Networking",
      "Real Estate"
    ],
    "can_help": "Mapping out the operational \"zero-to-one\" journey for international student relocation, validating market problems, and designing hybrid offline/online marketplace models in Germany.",
    "looking_for": "To connect with experienced founders, mentors, and peers who have navigated the 0-to-1 execution journey for hybrid marketplace or proptech models, and to gain actionable feedback as I scale NextKin from concept to on-ground execution.",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m068",
    "username": "laxmibharadwaj",
    "full_name": "Laxmibharadwaj",
    "headline": "I’ve 10+ years of IT experience in Various fields, Starting from Automotive to Cloud, K8's, DevOps, Cloud Security.",
    "company": "",
    "location": "",
    "bio": "I’ve 10+ years of IT experience in Various fields, Starting from Automotive to Cloud, K8's, DevOps, Cloud Security. Jack of all trades. King of only Few",
    "building": "GenAI 😂is everywhere , Also I know that most companies needs some AI products( from Agentic bots to help internal customers/ external, AI automation tools to automate their Workflows). I'm exploring GenAI with Vibe coding. bought a subscription for AI tool.",
    "skills": [
      "AI / GenAI",
      "Software",
      "Cloud / DevOps",
      "Product",
      "Automotive / Mobility",
      "Sales / GTM"
    ],
    "can_help": "I have a gift of great narration, Starting from Consulting, Explaining the product, Development, Debugging smooth workflow.",
    "looking_for": "I want to accumulate all the use cases or people who are enthusiastic like us in this group, Discuss the problems finalize an idea implement the solution. Then with help of any one who has sales experience. Build the brand to get new projects",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m069",
    "username": "jaysri",
    "full_name": "Jaysri",
    "headline": "I’m based in Munich. I have over 10 years of IT experience. Currently trying to establish myself as a freelancer and also looking for full time…",
    "company": "",
    "location": "Munich",
    "bio": "I’m based in Munich. I have over 10 years of IT experience. Currently trying to establish myself as a freelancer and also looking for full time opportunities",
    "building": "I too enjoy leveraging the AI space to develop apps, automating mundane tasks, etc. I am a Data Engineer. I worked on an app to teach math to a kid recently using AI",
    "skills": [
      "AI / GenAI",
      "Software",
      "Data / Analytics",
      "Engineering",
      "Community / Networking"
    ],
    "can_help": "I love Data and Analytics. I can provide ideas to build apps provided they are really meaningful and useful to the society",
    "looking_for": "I feel I am even more motivated to do such things when I have a group of like-minded people. This is a great forum. If there is a freelancer in the group already, please do ping me, I would be glad to connect and know more about it.",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m070",
    "username": "ateet.bahamani",
    "full_name": "Ateet Bahamani",
    "headline": "I’m based in Essen, Germany.",
    "company": "",
    "location": "Essen",
    "bio": "I’m based in Essen, Germany. I have 15+ years of IT experience. I’m a German citizen and currently looking for new opportunities (freelance and full-time)",
    "building": "Production-grade AI systems agentic workflows, RAG, and LLM automation. I’ve been building MASX AI (autonomous geopolitical forecasting) and reusable orchestration templates for multi-agent pipelines",
    "skills": [
      "AI / GenAI",
      "Data / Analytics",
      "Engineering",
      "Design / UX"
    ],
    "can_help": "End-to-end AI platform design and delivery: FastAPI + Pydantic services, LangChain/LangGraph/AutoGen integrations, vector search (Chroma/FAISS), and reliable data pipelines with CI/CD and observability",
    "looking_for": "Roles or collaborations where I can help ship real AI products into production. If you’re hiring or building something meaningful and need an AI architect/engineer, please message me",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m071",
    "username": "anita.bahmani",
    "full_name": "Anita Bahmani",
    "headline": "Physiotherapist based in Essen, Germany.",
    "company": "",
    "location": "Essen",
    "bio": "physiotherapist based in Essen, Germany. I live here with my family and have an 8-year-old son. I have 5 years of experience working in a German hospital and currently work at Elisabeth Krankenhaus",
    "building": "I’m focused on strengthening my clinical skills and growing professionally as a physiotherapist. My main interest is advanced rehabilitation and improving patient recovery outcomes. I’m not from an IT background, but I’m open to learning and meaningful collaboration",
    "skills": [
      "Healthcare / Life Sciences",
      "Education",
      "Community / Networking"
    ],
    "can_help": "Physiotherapy support and knowledge, especially in Manual Lymphatic Drainage (MLD), PNF, and neuropathy rehabilitation",
    "looking_for": "I’m looking to connect with like-minded people for collaboration, learning, and professional opportunities, especially in healthcare and rehabilitation",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m072",
    "username": "pritam.patil",
    "full_name": "Pritam Patil",
    "headline": "Everyone, my name is Pritam Patil, I live in Munich and work as Software Engineer",
    "company": "",
    "location": "Munich",
    "bio": "Hello Everyone, my name is Pritam Patil, I live in Munich and work as Software Engineer",
    "building": "Currently, I am building a platform for Indians- www.munichindians.com",
    "skills": [
      "Software",
      "Engineering",
      "Marketing / Growth"
    ],
    "can_help": "Website Development",
    "looking_for": "Digital Marketing, Performance Marketing superstars",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m073",
    "username": "arunkumar.sharma",
    "full_name": "Arunkumar Sharma",
    "headline": "I have over 16+ years of experience in the field of software building and problem solving..",
    "company": "",
    "location": "Berlin",
    "bio": "I have over 16+ years of experience in the field of software building and problem solving..\nI am currently in Berlin",
    "building": "I like to build solutions for day to day problems in the life of any person. \nI have a couple of ideas that I would like to work on.",
    "skills": [
      "Software",
      "Legal / Compliance"
    ],
    "can_help": "Android, and any technical problems related to it",
    "looking_for": "Guidance related to non technical and legal processes for my ideas.",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m074",
    "username": "payal.verma",
    "full_name": "Payal Verma",
    "headline": "I live in Augsburg (lived in munich for 8 years) and work as R&D Engineer",
    "company": "",
    "location": "Munich",
    "bio": "I live in Augsburg (lived in munich for 8 years) and work as R&D Engineer",
    "building": "I started working on 1-2 ideas but could not complete because of lack of time /strategy",
    "skills": [
      "Software",
      "Engineering",
      "Design / UX"
    ],
    "can_help": "I can help with: * frontend ,backend , mobile apps, database design",
    "looking_for": "open to collaborate based on my skillset",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  },
  {
    "id": "m075",
    "username": "himanshu",
    "full_name": "Himanshu",
    "headline": "I’m Himanshu (23), based in Munich.",
    "company": "",
    "location": "Munich",
    "bio": "I’m Himanshu (23), based in Munich. I study International Business and have been living in Germany for ~3.5 years, alongside building hands-on experience in the gastronomy industry",
    "building": "I’m obsessed with fixing how gastronomy actually works — moving from chaos to systems, scalability, and smart execution. I’m exploring ideas around tech-enabled food trucks, micro-kitchens, operational tools (POS/workflows, inventory & cost analytics), and alternative funding models for small food businesses",
    "skills": [
      "Data / Analytics",
      "Engineering",
      "Startups / Business",
      "Food / Retail"
    ],
    "can_help": "I sit at the intersection of kitchen execution and business strategy — cooking, menu engineering, food-cost optimization, supplier workflows, unit economics, and turning raw food ideas into structured, profitable, and scalable models",
    "looking_for": "A serious thinking partner / early collaborator to pressure-test ideas, iterate fast, and potentially co-build something meaningful in restaurants, food trucks, or food-tech — with a long-term mindset and strong execution focus",
    "linkedin_url": "",
    "website_url": "",
    "avatar_url": "",
    "status": "active"
  }
];
window.DEMO_MESSAGES = [];
